/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-sans)'],
        display: ['var(--font-display)'],
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        surface: { DEFAULT: 'hsl(var(--surface))', elevated: 'hsl(var(--surface-elevated))' },
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))', dim: 'hsl(var(--primary-dim) / 0.12)' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        cyan: { DEFAULT: 'hsl(var(--cyan))', foreground: 'hsl(var(--cyan-foreground))', dim: 'hsl(var(--cyan-dim) / 0.12)' },
        amber: { DEFAULT: 'hsl(var(--amber))', foreground: 'hsl(var(--amber-foreground))', dim: 'hsl(var(--amber-dim) / 0.12)' },
        pulse: { DEFAULT: 'hsl(var(--pulse))', foreground: 'hsl(var(--pulse-foreground))', dim: 'hsl(var(--pulse-dim) / 0.12)' },
        alert: { DEFAULT: 'hsl(var(--alert))', foreground: 'hsl(var(--alert-foreground))' },
        solo: { DEFAULT: 'hsl(var(--solo))', foreground: 'hsl(var(--solo-foreground))' },
        iso: { DEFAULT: 'hsl(var(--iso))', foreground: 'hsl(var(--iso-foreground))' },
        event: { DEFAULT: 'hsl(var(--event))', foreground: 'hsl(var(--event-foreground))' },
        success: { DEFAULT: 'hsl(var(--success))', foreground: 'hsl(var(--success-foreground))' },
        warning: { DEFAULT: 'hsl(var(--warning))', foreground: 'hsl(var(--warning-foreground))' },
        info: { DEFAULT: 'hsl(var(--info))', foreground: 'hsl(var(--info-foreground))' },
        /* New electric brand identity colors */
        'brand-neon': { DEFAULT: 'hsl(var(--brand-neon))', foreground: 'hsl(var(--primary-foreground))' },
        'brand-emergency': { DEFAULT: 'hsl(var(--brand-emergency))', foreground: 'hsl(var(--destructive-foreground))' },
        'brand-radar': { DEFAULT: 'hsl(var(--brand-radar))', foreground: 'hsl(var(--cyan-foreground))' },
        'brand-amber': { DEFAULT: 'hsl(var(--brand-amber))', foreground: 'hsl(var(--amber-foreground))' },
        /* Legacy brand aliases (backward compatible) */
        'brand-kawasaki': { DEFAULT: 'hsl(var(--brand-kawasaki))', foreground: 'hsl(var(--primary-foreground))' },
        'brand-yamaha': { DEFAULT: 'hsl(var(--brand-yamaha))', foreground: 'hsl(var(--primary-foreground))' },
        'brand-honda': { DEFAULT: 'hsl(var(--brand-honda))', foreground: 'hsl(var(--primary-foreground))' },
        'brand-ducati': { DEFAULT: 'hsl(var(--brand-ducati))', foreground: 'hsl(var(--primary-foreground))' },
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
        'fade-up': { from: { opacity: '0', transform: 'translateY(12px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'slide-in-right': { from: { opacity: '0', transform: 'translateX(20px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        'scale-in': { from: { opacity: '0', transform: 'scale(0.95)' }, to: { opacity: '1', transform: 'scale(1)' } },
        'radar-sweep': { '0%': { transform: 'rotate(0deg)' }, '100%': { transform: 'rotate(360deg)' } },
        'ekg-pulse': {
          '0%, 100%': { opacity: '0.4', transform: 'scaleY(0.85)' },
          '25%': { opacity: '1', transform: 'scaleY(1.05)' },
          '50%': { opacity: '0.6', transform: 'scaleY(0.95)' },
          '75%': { opacity: '1', transform: 'scaleY(1.08)' },
        },
        'neon-flicker': {
          '0%, 18%, 22%, 25%, 53%, 57%, 100%': { opacity: '1' },
          '20%, 24%, 55%': { opacity: '0.6' },
        },
        'glow-pulse': {
          '0%, 100%': { boxShadow: '0 0 12px hsl(var(--primary) / 0.4), 0 0 28px hsl(var(--primary) / 0.15)' },
          '50%': { boxShadow: '0 0 20px hsl(var(--primary) / 0.6), 0 0 40px hsl(var(--primary) / 0.25)' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'fade-in': 'fade-in 200ms ease-out',
        'fade-up': 'fade-up 300ms ease-out',
        'slide-in-right': 'slide-in-right 250ms ease-out',
        'scale-in': 'scale-in 200ms ease-out',
        'radar-sweep': 'radar-sweep 3s linear infinite',
        'ekg-pulse': 'ekg-pulse 2.4s ease-in-out infinite',
        'neon-flicker': 'neon-flicker 3s infinite alternate',
        'glow-pulse': 'glow-pulse 2s ease-in-out infinite',
      },
    },
  },
  safelist: [
    'bg-alert', 'text-alert-foreground', 'border-alert',
    'bg-solo', 'text-solo-foreground', 'border-solo',
    'bg-iso', 'text-iso-foreground', 'border-iso',
    'bg-event', 'text-event-foreground', 'border-event',
    'bg-brand-neon', 'text-brand-neon',
    'bg-brand-emergency', 'text-brand-emergency',
    'bg-brand-radar', 'text-brand-radar',
    'bg-brand-amber', 'text-brand-amber',
  ],
  plugins: [require("tailwindcss-animate")],
}
